const dotenv = require('dotenv');

dotenv.config();

const required = [
  'PORT',
  'COSMOS_CONNECTION_STRING',
  'COSMOS_DATABASE_NAME',
  'COSMOS_USERS_CONTAINER',
  'COSMOS_EVENTS_CONTAINER',
  'COSMOS_REGISTRATIONS_CONTAINER',
  'COSMOS_NOTIFICATIONS_CONTAINER',
  'JWT_SECRET',
  'JWT_EXPIRES_IN',
  'AZURE_STORAGE_CONNECTION_STRING',
  'REGISTRATION_NOTIFICATION_FUNCTION_URL',
  'EVENT_UPDATE_NOTIFICATION_FUNCTION_URL'
];

const missing = required.filter((key) => !process.env[key]);

if (missing.length > 0) {
  console.error(`Missing required environment variables: ${missing.join(', ')}`);
  process.exit(1);
}

module.exports = {
  PORT: parseInt(process.env.PORT, 10),
  COSMOS_CONNECTION_STRING: process.env.COSMOS_CONNECTION_STRING,
  COSMOS_DATABASE_NAME: process.env.COSMOS_DATABASE_NAME,
  COSMOS_USERS_CONTAINER: process.env.COSMOS_USERS_CONTAINER,
  COSMOS_EVENTS_CONTAINER: process.env.COSMOS_EVENTS_CONTAINER,
  COSMOS_REGISTRATIONS_CONTAINER: process.env.COSMOS_REGISTRATIONS_CONTAINER,
  COSMOS_NOTIFICATIONS_CONTAINER: process.env.COSMOS_NOTIFICATIONS_CONTAINER,
  AZURE_STORAGE_CONNECTION_STRING: process.env.AZURE_STORAGE_CONNECTION_STRING,
  REGISTRATION_NOTIFICATION_FUNCTION_URL: process.env.REGISTRATION_NOTIFICATION_FUNCTION_URL,
  EVENT_UPDATE_NOTIFICATION_FUNCTION_URL: process.env.EVENT_UPDATE_NOTIFICATION_FUNCTION_URL,
  APPLICATIONINSIGHTS_CONNECTION_STRING: process.env.APPLICATIONINSIGHTS_CONNECTION_STRING,
  JWT_SECRET: process.env.JWT_SECRET,
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
  NODE_ENV: process.env.NODE_ENV || 'development'
};
